/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@astrouxds/astro-web-components';


interface RuxClassificationMarkingProps {
  
  /** Defines which classification marking will be displayed. */
  classification?: Components.RuxClassificationMarking["classification"]
  
  /** Allows additional text labels to be added to the a marking */
  label?: Components.RuxClassificationMarking["label"]
  
  /** Declares the marking as a `tag` rather than the default banner style */
  tag?: Components.RuxClassificationMarking["tag"]
}

interface RuxClassificationMarkingEvents {
  
}

interface RuxClassificationMarkingSlots {
  default: any
}
  
/* generated by Svelte v3.42.3 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let rux_classification_marking;
	let current;
	const default_slot_template = /*#slots*/ ctx[6].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[5], null);

	return {
		c() {
			rux_classification_marking = element("rux-classification-marking");
			if (default_slot) default_slot.c();
			set_custom_element_data(rux_classification_marking, "classification", /*classification*/ ctx[0]);
			set_custom_element_data(rux_classification_marking, "label", /*label*/ ctx[1]);
			set_custom_element_data(rux_classification_marking, "tag", /*tag*/ ctx[2]);
		},
		m(target, anchor) {
			insert(target, rux_classification_marking, anchor);

			if (default_slot) {
				default_slot.m(rux_classification_marking, null);
			}

			/*rux_classification_marking_binding*/ ctx[7](rux_classification_marking);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 32)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[5],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[5])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[5], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*classification*/ 1) {
				set_custom_element_data(rux_classification_marking, "classification", /*classification*/ ctx[0]);
			}

			if (!current || dirty & /*label*/ 2) {
				set_custom_element_data(rux_classification_marking, "label", /*label*/ ctx[1]);
			}

			if (!current || dirty & /*tag*/ 4) {
				set_custom_element_data(rux_classification_marking, "tag", /*tag*/ ctx[2]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(rux_classification_marking);
			if (default_slot) default_slot.d(detaching);
			/*rux_classification_marking_binding*/ ctx[7](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { classification = undefined } = $$props;
	let { label = undefined } = $$props;
	let { tag = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(3, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function rux_classification_marking_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(3, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('classification' in $$props) $$invalidate(0, classification = $$props.classification);
		if ('label' in $$props) $$invalidate(1, label = $$props.label);
		if ('tag' in $$props) $$invalidate(2, tag = $$props.tag);
		if ('$$scope' in $$props) $$invalidate(5, $$scope = $$props.$$scope);
	};

	return [
		classification,
		label,
		tag,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		rux_classification_marking_binding
	];
}

class RuxClassificationMarking extends SvelteComponent {
  $$prop_def: RuxClassificationMarkingProps;
  $$events_def: RuxClassificationMarkingEvents;
  $$slot_def: RuxClassificationMarkingSlots;

  $on<K extends keyof RuxClassificationMarkingEvents>(type: K, callback: (e: RuxClassificationMarkingEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RuxClassificationMarkingProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			classification: 0,
			label: 1,
			tag: 2,
			getWebComponent: 4
		});
	}

	get classification() {
		return this.$$.ctx[0];
	}

	set classification(classification) {
		this.$$set({ classification });
		flush();
	}

	get label() {
		return this.$$.ctx[1];
	}

	set label(label) {
		this.$$set({ label });
		flush();
	}

	get tag() {
		return this.$$.ctx[2];
	}

	set tag(tag) {
		this.$$set({ tag });
		flush();
	}

	get getWebComponent(): HTMLRuxClassificationMarkingElement | undefined {
		return this.$$.ctx[4];
	}
}

export default RuxClassificationMarking;