/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@astrouxds/astro-web-components';


interface RuxRadioGroupProps {
  
  /** The label of the radio group */
  label?: Components.RuxRadioGroup["label"]
  
  /** Marks the radio group as invalid */
  invalid?: Components.RuxRadioGroup["invalid"]
  
  /** The name of the radio group - submitted with form data. Must match the name of the radios in the group. */
  name?: Components.RuxRadioGroup["name"]
  
  /** The value of the current selected radio in the group. Changing this will also mark that radio as checked in the UI. */
  value?: Components.RuxRadioGroup["value"]
  
  /** The help or explanation text */
  helpText?: Components.RuxRadioGroup["helpText"]
  
  /** The validation error text */
  errorText?: Components.RuxRadioGroup["errorText"]
}

interface RuxRadioGroupEvents {
  
  /** Fired when the value of the input changes - [HTMLElement/input_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) */
  "rux-change": Parameters<JSX.RuxRadioGroup["onRux-change"]>[0]
}

interface RuxRadioGroupSlots {
  default: any
}
  
/* generated by Svelte v3.42.3 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let rux_radio_group;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[10].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[9], null);

	return {
		c() {
			rux_radio_group = element("rux-radio-group");
			if (default_slot) default_slot.c();
			set_custom_element_data(rux_radio_group, "label", /*label*/ ctx[0]);
			set_custom_element_data(rux_radio_group, "invalid", /*invalid*/ ctx[1]);
			set_custom_element_data(rux_radio_group, "name", /*name*/ ctx[2]);
			set_custom_element_data(rux_radio_group, "value", /*value*/ ctx[3]);
			set_custom_element_data(rux_radio_group, "help-text", /*helpText*/ ctx[4]);
			set_custom_element_data(rux_radio_group, "error-text", /*errorText*/ ctx[5]);
		},
		m(target, anchor) {
			insert(target, rux_radio_group, anchor);

			if (default_slot) {
				default_slot.m(rux_radio_group, null);
			}

			/*rux_radio_group_binding*/ ctx[11](rux_radio_group);
			current = true;

			if (!mounted) {
				dispose = listen(rux_radio_group, "rux-change", /*onEvent*/ ctx[7]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 512)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[9],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[9])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[9], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*label*/ 1) {
				set_custom_element_data(rux_radio_group, "label", /*label*/ ctx[0]);
			}

			if (!current || dirty & /*invalid*/ 2) {
				set_custom_element_data(rux_radio_group, "invalid", /*invalid*/ ctx[1]);
			}

			if (!current || dirty & /*name*/ 4) {
				set_custom_element_data(rux_radio_group, "name", /*name*/ ctx[2]);
			}

			if (!current || dirty & /*value*/ 8) {
				set_custom_element_data(rux_radio_group, "value", /*value*/ ctx[3]);
			}

			if (!current || dirty & /*helpText*/ 16) {
				set_custom_element_data(rux_radio_group, "help-text", /*helpText*/ ctx[4]);
			}

			if (!current || dirty & /*errorText*/ 32) {
				set_custom_element_data(rux_radio_group, "error-text", /*errorText*/ ctx[5]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(rux_radio_group);
			if (default_slot) default_slot.d(detaching);
			/*rux_radio_group_binding*/ ctx[11](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { label = undefined } = $$props;
	let { invalid = undefined } = $$props;
	let { name = undefined } = $$props;
	let { value = undefined } = $$props;
	let { helpText = undefined } = $$props;
	let { errorText = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(6, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function rux_radio_group_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(6, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('label' in $$props) $$invalidate(0, label = $$props.label);
		if ('invalid' in $$props) $$invalidate(1, invalid = $$props.invalid);
		if ('name' in $$props) $$invalidate(2, name = $$props.name);
		if ('value' in $$props) $$invalidate(3, value = $$props.value);
		if ('helpText' in $$props) $$invalidate(4, helpText = $$props.helpText);
		if ('errorText' in $$props) $$invalidate(5, errorText = $$props.errorText);
		if ('$$scope' in $$props) $$invalidate(9, $$scope = $$props.$$scope);
	};

	return [
		label,
		invalid,
		name,
		value,
		helpText,
		errorText,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		slots,
		rux_radio_group_binding
	];
}

class RuxRadioGroup extends SvelteComponent {
  $$prop_def: RuxRadioGroupProps;
  $$events_def: RuxRadioGroupEvents;
  $$slot_def: RuxRadioGroupSlots;

  $on<K extends keyof RuxRadioGroupEvents>(type: K, callback: (e: RuxRadioGroupEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RuxRadioGroupProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			label: 0,
			invalid: 1,
			name: 2,
			value: 3,
			helpText: 4,
			errorText: 5,
			getWebComponent: 8
		});
	}

	get label() {
		return this.$$.ctx[0];
	}

	set label(label) {
		this.$$set({ label });
		flush();
	}

	get invalid() {
		return this.$$.ctx[1];
	}

	set invalid(invalid) {
		this.$$set({ invalid });
		flush();
	}

	get name() {
		return this.$$.ctx[2];
	}

	set name(name) {
		this.$$set({ name });
		flush();
	}

	get value() {
		return this.$$.ctx[3];
	}

	set value(value) {
		this.$$set({ value });
		flush();
	}

	get helpText() {
		return this.$$.ctx[4];
	}

	set helpText(helpText) {
		this.$$set({ helpText });
		flush();
	}

	get errorText() {
		return this.$$.ctx[5];
	}

	set errorText(errorText) {
		this.$$set({ errorText });
		flush();
	}

	get getWebComponent(): HTMLRuxRadioGroupElement | undefined {
		return this.$$.ctx[8];
	}
}

export default RuxRadioGroup;