/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@astrouxds/astro-web-components';


interface RuxRadioProps {
  
  /** The radio name */
  name?: Components.RuxRadio["name"]
  
  /** The radio value */
  value?: Components.RuxRadio["value"]
  
  /** Toggles checked state of a radio */
  checked?: Components.RuxRadio["checked"]
  
  /** Disables the radio via HTML disabled attribute. Radio takes on a distinct visual state. Cursor uses the not-allowed system replacement and all keyboard and mouse events are ignored. */
  disabled?: Components.RuxRadio["disabled"]
}

interface RuxRadioEvents {
  
  /** Fired when the value of the input changes - [HTMLElement/input_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) */
  "rux-change": Parameters<JSX.RuxRadio["onRux-change"]>[0]
}

interface RuxRadioSlots {
  default: any
}
  
/* generated by Svelte v3.42.3 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let rux_radio;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[8].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[7], null);

	return {
		c() {
			rux_radio = element("rux-radio");
			if (default_slot) default_slot.c();
			set_custom_element_data(rux_radio, "name", /*name*/ ctx[0]);
			set_custom_element_data(rux_radio, "value", /*value*/ ctx[1]);
			set_custom_element_data(rux_radio, "checked", /*checked*/ ctx[2]);
			set_custom_element_data(rux_radio, "disabled", /*disabled*/ ctx[3]);
		},
		m(target, anchor) {
			insert(target, rux_radio, anchor);

			if (default_slot) {
				default_slot.m(rux_radio, null);
			}

			/*rux_radio_binding*/ ctx[9](rux_radio);
			current = true;

			if (!mounted) {
				dispose = listen(rux_radio, "rux-change", /*onEvent*/ ctx[5]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 128)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[7],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[7])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[7], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*name*/ 1) {
				set_custom_element_data(rux_radio, "name", /*name*/ ctx[0]);
			}

			if (!current || dirty & /*value*/ 2) {
				set_custom_element_data(rux_radio, "value", /*value*/ ctx[1]);
			}

			if (!current || dirty & /*checked*/ 4) {
				set_custom_element_data(rux_radio, "checked", /*checked*/ ctx[2]);
			}

			if (!current || dirty & /*disabled*/ 8) {
				set_custom_element_data(rux_radio, "disabled", /*disabled*/ ctx[3]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(rux_radio);
			if (default_slot) default_slot.d(detaching);
			/*rux_radio_binding*/ ctx[9](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { name = undefined } = $$props;
	let { value = undefined } = $$props;
	let { checked = undefined } = $$props;
	let { disabled = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(4, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function rux_radio_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(4, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('name' in $$props) $$invalidate(0, name = $$props.name);
		if ('value' in $$props) $$invalidate(1, value = $$props.value);
		if ('checked' in $$props) $$invalidate(2, checked = $$props.checked);
		if ('disabled' in $$props) $$invalidate(3, disabled = $$props.disabled);
		if ('$$scope' in $$props) $$invalidate(7, $$scope = $$props.$$scope);
	};

	return [
		name,
		value,
		checked,
		disabled,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		slots,
		rux_radio_binding
	];
}

class RuxRadio extends SvelteComponent {
  $$prop_def: RuxRadioProps;
  $$events_def: RuxRadioEvents;
  $$slot_def: RuxRadioSlots;

  $on<K extends keyof RuxRadioEvents>(type: K, callback: (e: RuxRadioEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RuxRadioProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			name: 0,
			value: 1,
			checked: 2,
			disabled: 3,
			getWebComponent: 6
		});
	}

	get name() {
		return this.$$.ctx[0];
	}

	set name(name) {
		this.$$set({ name });
		flush();
	}

	get value() {
		return this.$$.ctx[1];
	}

	set value(value) {
		this.$$set({ value });
		flush();
	}

	get checked() {
		return this.$$.ctx[2];
	}

	set checked(checked) {
		this.$$set({ checked });
		flush();
	}

	get disabled() {
		return this.$$.ctx[3];
	}

	set disabled(disabled) {
		this.$$set({ disabled });
		flush();
	}

	get getWebComponent(): HTMLRuxRadioElement | undefined {
		return this.$$.ctx[6];
	}
}

export default RuxRadio;