/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@astrouxds/astro-web-components';


interface RuxSelectProps {
  
  /** Disables the item */
  disabled?: Components.RuxSelect["disabled"]
  
  /** Sets the field as required */
  required?: Components.RuxSelect["required"]
  
  /** Sets the Label for the Select */
  label?: Components.RuxSelect["label"]
  
  /** Id for the Select Input */
  inputId?: Components.RuxSelect["inputId"]
  
  /** Id for the Label */
  labelId?: Components.RuxSelect["labelId"]
  
  /** Sets the Select as Invalid for Custom Validation Usage */
  invalid?: Components.RuxSelect["invalid"]
  
  /** Sets the Name of the Input Element */
  name?: Components.RuxSelect["name"]
}

interface RuxSelectEvents {
  
  /** Event Emitted when the Value of the Select is Changed */
  "rux-change": Parameters<JSX.RuxSelect["onRux-change"]>[0]
}

interface RuxSelectSlots {
  default: any
}
  
/* generated by Svelte v3.42.3 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let rux_select;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[11].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[10], null);

	return {
		c() {
			rux_select = element("rux-select");
			if (default_slot) default_slot.c();
			set_custom_element_data(rux_select, "disabled", /*disabled*/ ctx[0]);
			set_custom_element_data(rux_select, "required", /*required*/ ctx[1]);
			set_custom_element_data(rux_select, "label", /*label*/ ctx[2]);
			set_custom_element_data(rux_select, "input-id", /*inputId*/ ctx[3]);
			set_custom_element_data(rux_select, "label-id", /*labelId*/ ctx[4]);
			set_custom_element_data(rux_select, "invalid", /*invalid*/ ctx[5]);
			set_custom_element_data(rux_select, "name", /*name*/ ctx[6]);
		},
		m(target, anchor) {
			insert(target, rux_select, anchor);

			if (default_slot) {
				default_slot.m(rux_select, null);
			}

			/*rux_select_binding*/ ctx[12](rux_select);
			current = true;

			if (!mounted) {
				dispose = listen(rux_select, "rux-change", /*onEvent*/ ctx[8]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 1024)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[10],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[10])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[10], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*disabled*/ 1) {
				set_custom_element_data(rux_select, "disabled", /*disabled*/ ctx[0]);
			}

			if (!current || dirty & /*required*/ 2) {
				set_custom_element_data(rux_select, "required", /*required*/ ctx[1]);
			}

			if (!current || dirty & /*label*/ 4) {
				set_custom_element_data(rux_select, "label", /*label*/ ctx[2]);
			}

			if (!current || dirty & /*inputId*/ 8) {
				set_custom_element_data(rux_select, "input-id", /*inputId*/ ctx[3]);
			}

			if (!current || dirty & /*labelId*/ 16) {
				set_custom_element_data(rux_select, "label-id", /*labelId*/ ctx[4]);
			}

			if (!current || dirty & /*invalid*/ 32) {
				set_custom_element_data(rux_select, "invalid", /*invalid*/ ctx[5]);
			}

			if (!current || dirty & /*name*/ 64) {
				set_custom_element_data(rux_select, "name", /*name*/ ctx[6]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(rux_select);
			if (default_slot) default_slot.d(detaching);
			/*rux_select_binding*/ ctx[12](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { disabled = undefined } = $$props;
	let { required = undefined } = $$props;
	let { label = undefined } = $$props;
	let { inputId = undefined } = $$props;
	let { labelId = undefined } = $$props;
	let { invalid = undefined } = $$props;
	let { name = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(7, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function rux_select_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(7, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('disabled' in $$props) $$invalidate(0, disabled = $$props.disabled);
		if ('required' in $$props) $$invalidate(1, required = $$props.required);
		if ('label' in $$props) $$invalidate(2, label = $$props.label);
		if ('inputId' in $$props) $$invalidate(3, inputId = $$props.inputId);
		if ('labelId' in $$props) $$invalidate(4, labelId = $$props.labelId);
		if ('invalid' in $$props) $$invalidate(5, invalid = $$props.invalid);
		if ('name' in $$props) $$invalidate(6, name = $$props.name);
		if ('$$scope' in $$props) $$invalidate(10, $$scope = $$props.$$scope);
	};

	return [
		disabled,
		required,
		label,
		inputId,
		labelId,
		invalid,
		name,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		slots,
		rux_select_binding
	];
}

class RuxSelect extends SvelteComponent {
  $$prop_def: RuxSelectProps;
  $$events_def: RuxSelectEvents;
  $$slot_def: RuxSelectSlots;

  $on<K extends keyof RuxSelectEvents>(type: K, callback: (e: RuxSelectEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RuxSelectProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			disabled: 0,
			required: 1,
			label: 2,
			inputId: 3,
			labelId: 4,
			invalid: 5,
			name: 6,
			getWebComponent: 9
		});
	}

	get disabled() {
		return this.$$.ctx[0];
	}

	set disabled(disabled) {
		this.$$set({ disabled });
		flush();
	}

	get required() {
		return this.$$.ctx[1];
	}

	set required(required) {
		this.$$set({ required });
		flush();
	}

	get label() {
		return this.$$.ctx[2];
	}

	set label(label) {
		this.$$set({ label });
		flush();
	}

	get inputId() {
		return this.$$.ctx[3];
	}

	set inputId(inputId) {
		this.$$set({ inputId });
		flush();
	}

	get labelId() {
		return this.$$.ctx[4];
	}

	set labelId(labelId) {
		this.$$set({ labelId });
		flush();
	}

	get invalid() {
		return this.$$.ctx[5];
	}

	set invalid(invalid) {
		this.$$set({ invalid });
		flush();
	}

	get name() {
		return this.$$.ctx[6];
	}

	set name(name) {
		this.$$set({ name });
		flush();
	}

	get getWebComponent(): HTMLRuxSelectElement | undefined {
		return this.$$.ctx[9];
	}
}

export default RuxSelect;