/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@astrouxds/astro-web-components';


interface RuxSliderProps {
  
  /** Min value of the slider. */
  min?: Components.RuxSlider["min"]
  
  /** Max value of slider. */
  max?: Components.RuxSlider["max"]
  
  /** Step amount of slider value. */
  step?: Components.RuxSlider["step"]
  
  /** Current value of the slider. The default value is halfway between the specified minimum and maximum. - [HTMLElement/<input type="range">](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) */
  value?: Components.RuxSlider["value"]
  
  /** Determines if the slider is disabled. */
  disabled?: Components.RuxSlider["disabled"]
  
  /** Name of the Input Field for Form Submission */
  name?: Components.RuxSlider["name"]
}

interface RuxSliderEvents {
  
  /** Fired when the value of the input changes - [HTMLElement/input_event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event) */
  "rux-input": Parameters<JSX.RuxSlider["onRux-input"]>[0]
}

interface RuxSliderSlots {
  default: any
}
  
/* generated by Svelte v3.42.3 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let rux_slider;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[10].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[9], null);

	return {
		c() {
			rux_slider = element("rux-slider");
			if (default_slot) default_slot.c();
			set_custom_element_data(rux_slider, "min", /*min*/ ctx[0]);
			set_custom_element_data(rux_slider, "max", /*max*/ ctx[1]);
			set_custom_element_data(rux_slider, "step", /*step*/ ctx[2]);
			set_custom_element_data(rux_slider, "value", /*value*/ ctx[3]);
			set_custom_element_data(rux_slider, "disabled", /*disabled*/ ctx[4]);
			set_custom_element_data(rux_slider, "name", /*name*/ ctx[5]);
		},
		m(target, anchor) {
			insert(target, rux_slider, anchor);

			if (default_slot) {
				default_slot.m(rux_slider, null);
			}

			/*rux_slider_binding*/ ctx[11](rux_slider);
			current = true;

			if (!mounted) {
				dispose = listen(rux_slider, "rux-input", /*onEvent*/ ctx[7]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 512)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[9],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[9])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[9], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*min*/ 1) {
				set_custom_element_data(rux_slider, "min", /*min*/ ctx[0]);
			}

			if (!current || dirty & /*max*/ 2) {
				set_custom_element_data(rux_slider, "max", /*max*/ ctx[1]);
			}

			if (!current || dirty & /*step*/ 4) {
				set_custom_element_data(rux_slider, "step", /*step*/ ctx[2]);
			}

			if (!current || dirty & /*value*/ 8) {
				set_custom_element_data(rux_slider, "value", /*value*/ ctx[3]);
			}

			if (!current || dirty & /*disabled*/ 16) {
				set_custom_element_data(rux_slider, "disabled", /*disabled*/ ctx[4]);
			}

			if (!current || dirty & /*name*/ 32) {
				set_custom_element_data(rux_slider, "name", /*name*/ ctx[5]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(rux_slider);
			if (default_slot) default_slot.d(detaching);
			/*rux_slider_binding*/ ctx[11](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { min = undefined } = $$props;
	let { max = undefined } = $$props;
	let { step = undefined } = $$props;
	let { value = undefined } = $$props;
	let { disabled = undefined } = $$props;
	let { name = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(6, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function rux_slider_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(6, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('min' in $$props) $$invalidate(0, min = $$props.min);
		if ('max' in $$props) $$invalidate(1, max = $$props.max);
		if ('step' in $$props) $$invalidate(2, step = $$props.step);
		if ('value' in $$props) $$invalidate(3, value = $$props.value);
		if ('disabled' in $$props) $$invalidate(4, disabled = $$props.disabled);
		if ('name' in $$props) $$invalidate(5, name = $$props.name);
		if ('$$scope' in $$props) $$invalidate(9, $$scope = $$props.$$scope);
	};

	return [
		min,
		max,
		step,
		value,
		disabled,
		name,
		__ref,
		onEvent,
		getWebComponent,
		$$scope,
		slots,
		rux_slider_binding
	];
}

class RuxSlider extends SvelteComponent {
  $$prop_def: RuxSliderProps;
  $$events_def: RuxSliderEvents;
  $$slot_def: RuxSliderSlots;

  $on<K extends keyof RuxSliderEvents>(type: K, callback: (e: RuxSliderEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RuxSliderProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			min: 0,
			max: 1,
			step: 2,
			value: 3,
			disabled: 4,
			name: 5,
			getWebComponent: 8
		});
	}

	get min() {
		return this.$$.ctx[0];
	}

	set min(min) {
		this.$$set({ min });
		flush();
	}

	get max() {
		return this.$$.ctx[1];
	}

	set max(max) {
		this.$$set({ max });
		flush();
	}

	get step() {
		return this.$$.ctx[2];
	}

	set step(step) {
		this.$$set({ step });
		flush();
	}

	get value() {
		return this.$$.ctx[3];
	}

	set value(value) {
		this.$$set({ value });
		flush();
	}

	get disabled() {
		return this.$$.ctx[4];
	}

	set disabled(disabled) {
		this.$$set({ disabled });
		flush();
	}

	get name() {
		return this.$$.ctx[5];
	}

	set name(name) {
		this.$$set({ name });
		flush();
	}

	get getWebComponent(): HTMLRuxSliderElement | undefined {
		return this.$$.ctx[8];
	}
}

export default RuxSlider;