/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@astrouxds/astro-web-components';


interface RuxTabPanelsProps {
  
}

interface RuxTabPanelsEvents {
  
  /** Emits a list of the Tab Panels that have been passed in */
  "rux-register-panels": Parameters<JSX.RuxTabPanels["onRux-register-panels"]>[0]
}

interface RuxTabPanelsSlots {
  default: any
}
  
/* generated by Svelte v3.42.3 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	listen,
	safe_not_equal,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let rux_tab_panels;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	return {
		c() {
			rux_tab_panels = element("rux-tab-panels");
			if (default_slot) default_slot.c();
		},
		m(target, anchor) {
			insert(target, rux_tab_panels, anchor);

			if (default_slot) {
				default_slot.m(rux_tab_panels, null);
			}

			/*rux_tab_panels_binding*/ ctx[5](rux_tab_panels);
			current = true;

			if (!mounted) {
				dispose = listen(rux_tab_panels, "rux-register-panels", /*onEvent*/ ctx[1]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 8)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[3],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[3])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[3], dirty, null),
						null
					);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(rux_tab_panels);
			if (default_slot) default_slot.d(detaching);
			/*rux_tab_panels_binding*/ ctx[5](null);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(0, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function rux_tab_panels_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(0, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('$$scope' in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	return [__ref, onEvent, getWebComponent, $$scope, slots, rux_tab_panels_binding];
}

class RuxTabPanels extends SvelteComponent {
  $$prop_def: RuxTabPanelsProps;
  $$events_def: RuxTabPanelsEvents;
  $$slot_def: RuxTabPanelsSlots;

  $on<K extends keyof RuxTabPanelsEvents>(type: K, callback: (e: RuxTabPanelsEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<RuxTabPanelsProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { getWebComponent: 2 });
	}

	get getWebComponent(): HTMLRuxTabPanelsElement | undefined {
		return this.$$.ctx[2];
	}
}

export default RuxTabPanels;